# Generated by Django 6.0.6 on 2026-06-24 17:13

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='academictask',
            name='grade',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='academictask',
            name='reminder_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='academictask',
            name='weight_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='academictask',
            name='progress_percentage',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='academictask',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.AddIndex(
            model_name='academictask',
            index=models.Index(fields=['user', 'status'], name='academic_ac_user_id_7524a1_idx'),
        ),
        migrations.AddIndex(
            model_name='academictask',
            index=models.Index(fields=['user', 'due_date'], name='academic_ac_user_id_16649c_idx'),
        ),
        migrations.AddIndex(
            model_name='academictask',
            index=models.Index(fields=['user', 'priority'], name='academic_ac_user_id_62e556_idx'),
        ),
    ]
